#!/usr/bin/env node

import { spawnSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { getSupabaseBin, projectRoot } from './lib/paths.mjs';

const root = projectRoot;
const envLocalPath = join(root, '.env.local');

const SUPABASE_KEYS = {
  API_URL: 'NEXT_PUBLIC_SUPABASE_URL',
  ANON_KEY: 'NEXT_PUBLIC_SUPABASE_ANON_KEY',
  SERVICE_ROLE_KEY: 'SUPABASE_SERVICE_ROLE_KEY',
};

const PRESERVED_KEYS = new Set([
  'NEXT_PUBLIC_SUPABASE_URL',
  'NEXT_PUBLIC_SUPABASE_ANON_KEY',
  'SUPABASE_SERVICE_ROLE_KEY',
  'OPENROUTER_API_KEY',
  'OPENROUTER_BASE_URL',
]);

function parseEnvFile(contents) {
  const entries = new Map();

  for (const line of contents.split('\n')) {
    const trimmed = line.trim();

    if (!trimmed || trimmed.startsWith('#')) {
      continue;
    }

    const separator = trimmed.indexOf('=');

    if (separator === -1) {
      continue;
    }

    const key = trimmed.slice(0, separator).trim();
    const value = trimmed.slice(separator + 1).trim();
    entries.set(key, value);
  }

  return entries;
}

function parseSupabaseStatus(output) {
  const values = {};

  for (const line of output.split('\n')) {
    const match = line.match(/^([A-Z_]+)="(.*)"$/);

    if (match) {
      values[match[1]] = match[2];
    }
  }

  return values;
}

function readExistingEnv() {
  const sources = [envLocalPath, join(root, '.env.example')];
  const merged = new Map();

  for (const source of sources) {
    if (!existsSync(source)) {
      continue;
    }

    for (const [key, value] of parseEnvFile(readFileSync(source, 'utf8'))) {
      if (!merged.has(key)) {
        merged.set(key, value);
      }
    }
  }

  return merged;
}

export function syncSupabaseEnv() {
  const supabaseBin = getSupabaseBin();

  if (!supabaseBin) {
    throw new Error('Supabase CLI not found. Run `npm install` first.');
  }

  const status = spawnSync(supabaseBin, ['status', '-o', 'env'], {
    cwd: root,
    encoding: 'utf8',
  });

  if (status.status !== 0) {
    throw new Error(status.stderr || 'Failed to read Supabase status');
  }

  const supabaseValues = parseSupabaseStatus(status.stdout);
  const env = readExistingEnv();

  for (const [sourceKey, targetKey] of Object.entries(SUPABASE_KEYS)) {
    if (supabaseValues[sourceKey]) {
      env.set(targetKey, supabaseValues[sourceKey]);
    }
  }

  if (!env.has('OPENROUTER_BASE_URL')) {
    env.set('OPENROUTER_BASE_URL', 'https://openrouter.ai/api/v1');
  }

  const lines = [
    '# Generated by scripts/sync-env.mjs — Supabase keys update on each `npm run dev`.',
    '# Add OPENROUTER_API_KEY and other secrets here; they are preserved across syncs.',
    '',
  ];

  for (const key of PRESERVED_KEYS) {
    if (env.has(key)) {
      lines.push(`${key}=${env.get(key)}`);
    }
  }

  for (const [key, value] of env) {
    if (!PRESERVED_KEYS.has(key)) {
      lines.push(`${key}=${value}`);
    }
  }

  writeFileSync(envLocalPath, `${lines.join('\n')}\n`, 'utf8');
  console.log('[supabase] Wrote local credentials to .env.local');
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href) {
  syncSupabaseEnv();
}
